### PR TITLE
🐛 Validate container image and tags

### LINKED ISSUE #755: UI: Validate container image name to prevent colon in repository name
## Problem

When deploying agents or tools from container images via the UI, the "Container Image" field accepts any string, including colons (`:`). Since the UI separately appends the image tag as `${containerImage}:${imageTag}`, entering a colon in the image name (e.g., `quay.io/myorg/my-tool:latest`) produces a double-tagged reference like `quay.io/myorg/my-tool:latest:v0.0.1`.

Kubernetes rejects this as `InvalidImageName`, but the error only surfaces in the pod status — there is no error visible in the Kagenti UI. The agent or tool gets stuck in "Progressing" state with no indication of what went wrong.

## Expected Behavior

The UI should validate the "Container Image" field against the [OCI distribution-spec repository name grammar](https://github.com/opencontainers/distribution-spec/blob/main/spec.md#workflow-categories):

```
<repository-name> := [a-z0-9]+((\.|_|__|-+)[a-z0-9]+)*(\/[a-z0-9]+((\.|_|__|-+)[a-z0-9]+)*)*
```

At minimum, the image name field should:
1. **Reject colons** (`:`) in the container image name — the tag is entered in a separate field
2. **Show an inline validation error** when the image name contains invalid characters
3. **Prevent form submission** if the image name is invalid

## Current Behavior

- User enters image name with a colon (e.g., `quay.io/myorg/my-tool:latest`)
- UI appends the tag from the separate "Image Tag" field, producing `quay.io/myorg/my-tool:latest:v0.0.1`
- Kubernetes reports `InvalidImageName` on the pod
- The agent/tool status shows "Progressing" indefinitely with no UI-visible error

## Affected Files

- `kagenti/ui-v2/src/pages/ImportToolPage.tsx` — `handleImageChange()` and `validateForm()` (around lines 219-224 and 383-391)
- `kagenti/ui-v2/src/pages/ImportAgentPage.tsx` — `handleImageChange()` and `validateForm()` (around lines 219-226 and 403-411)

Both files combine the image name and tag in `handleSubmit`:
```typescript
const fullImage = imageTag ? `${containerImage}:${imageTag}` : containerImage;
```

## Suggested Implementation

Add validation to the `containerImage` field similar to the existing `isValidEnvVarName` pattern already used in both files. For example:

```typescript
const isValidImageName = (image: string): boolean => {
  if (!image) return false;
  // OCI distribution-spec repository name pattern (no colon allowed)
  const pattern = /^[a-z0-9]+((\.|_|__|-+)[a-z0-9]+)*(\/[a-z0-9]+((\.|_|__|-+)[a-z0-9]+)*)*$/;
  return pattern.test(image);
};
```

Update the `validated.containerImage` check in `validateForm()` to reject invalid image names, and show an appropriate error message in the form helper text.

## References

- OCI Distribution Spec — repository names: https://github.com/opencontainers/distribution-spec/blob/main/spec.md#workflow-categories
- Repository name regex: `[a-z0-9]+((\.|_|__|-+)[a-z0-9]+)*(\/[a-z0-9]+((\.|_|__|-+)[a-z0-9]+)*)*`

### PR DESCRIPTION
**Pull request by esnible**
## Summary

Add client-side validation for container image name and tag fields on the Import Tool and Import Agent pages. The image name is validated against the OCI distribution-spec repository name grammar, and the image tag is validated against the OCI tag format. This prevents users from entering colons or other invalid characters that cause Kubernetes `InvalidImageName` errors, leaving agents/tools stuck on "Progressing" with no UI-visible error.

Key changes:
- Add `isValidImageName()` validation
- Add `isValidImageTag()` validation
- Update `validateForm()` to reject invalid image names and tags before submission
- Show inline error messages with guidance on allowed characters
- Add test cases

## Related issue(s)

Resolves #755
Mitigates #636
Replaces https://github.com/kagenti/kagenti/pull/756

### CODE REVIEW

File: kagenti/ui-v2/src/utils/validation.ts [hunk 1]
```diff
@@ -12,3 +12,42 @@ export const isValidEnvVarName = (name: string): boolean => {
...
+
+/**
+ * Validate an image tag.
+ *
+ * Must be valid ASCII containing only letters, digits, underscores,
+ * periods, and dashes. May not start with a period or a dash.
+ */
+export const isValidImageTag = (tag: string): boolean => {
+  if (!tag) return false;
+  return /^[a-zA-Z0-9_][a-zA-Z0-9._-]*$/.test(tag);
```
Comment (pdettori) [inline kagenti/ui-v2/src/utils/validation.ts:52]: **suggestion**: The OCI distribution-spec limits tags to 128 characters. Currently a 200-char tag would pass client validation but fail in Kubernetes — partially defeating the purpose of client-side validation.

Consider adding a length check:

```ts
if (tag.length > 128) return false;
```

Or adjust the regex to `/^[a-zA-Z0-9_][a-zA-Z0-9._-]{0,127}$/`.

File: kagenti/ui-v2/src/utils/validation.test.ts [hunk 2]
```diff
@@ -45,3 +45,121 @@ describe('isValidEnvVarName', () => {
...
+    expect(isValidImageTag(' latest')).toBe(false);
+  });
+
+  it('rejects tags with non-ASCII or special characters', () => {
+    expect(isValidImageTag('tag@1')).toBe(false);
+    expect(isValidImageTag('tag:1')).toBe(false);
+    expect(isValidImageTag('tag/1')).toBe(false);
+    expect(isValidImageTag('tag!')).toBe(false);
+    expect(isValidImageTag('tàg')).toBe(false);
+  });
```
Comment (pdettori) [inline kagenti/ui-v2/src/utils/validation.test.ts:164]: **suggestion**: Consider adding boundary tests for tag length once the 128-char limit is added:

```ts
it('accepts tag at max length (128 chars)', () => {
  expect(isValidImageTag('a'.repeat(128))).toBe(true);
});

it('rejects tag exceeding max length', () => {
  expect(isValidImageTag('a'.repeat(129))).toBe(false);
});
```
