### PR TITLE
Fix: Add MLflow to dashboard

### LINKED ISSUE #1108: bug: MLFlow link
### Feature Description

Currently, Kagenti's http://kagenti-ui.localtest.me:8080/observability page shows the observability tools Phoenix and Kiali.  Because Kagenti's charts now allow MLFlow to be installed, perhaps it should be there, to let users know how to find it.

Kagenti's [MLFlow docs](https://github.com/kagenti/kagenti/blob/5a3eab8d1c4267defe3dbfe9e78c5a3917c77366/docs/mlflow-integration.md) do not indicate how to install MLFlow.  I needed help to find it.  Here is what I did:

```bash
cat <<EOF > /tmp/enable-phoenix-and-mlflow.yaml
charts:
  kagenti-deps:
    values:
      components:
        phoenix:
          enabled: true
        mlflow:
          enabled: true
    values:
      components:
        phoenix:
          enabled: true
        mlflow:
          enabled: true
EOF

deployments/ansible/run-install.sh --env dev --env-file /tmp/enable-phoenix-and-mlflow.yaml
```

It might be worthwhile to either make it easier to install MLFlow or document the two places that need to be enabled.

Possibly instead of a Boolean `true` we should specify a URL in one of those places, to support custom endpoints when MLFlow is installed using Kagenti's charts on OpenShift, or when a non-Kagenti MLFlow installation is used.

### Proposed Solution

- Kagenti should create an MLFlow tile if MLFlow is enabled
- Document the MLFlow flags in Kagenti's installation charts.

### Want to contribute?

- [ ] I would like to work on this issue.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by esnible**
## Summary

Resolves #1108 by adding a new card to the UI.

## (Optional) Testing Instructions

Install Kagenti with MLflow.  Visit the dashboard ( http://kagenti-ui.localtest.me:8080/observability ) and verify a UI panel and link appears.

### CODE REVIEW

File: kagenti/ui-v2/src/pages/ObservabilityPage.tsx [hunk 1]
```diff
@@ -144,18 +146,45 @@ export const ObservabilityPage: React.FC = () => {
...
-          variant="info"
-          title="Note"
-          isInline
-          style={{ marginTop: '24px' }}
-        >
-          Ensure that the observability tools ({tracesUrl ? 'Phoenix for traces and ' : ''}Kiali for
-          service mesh) are properly configured and accessible from your
-          environment.
-        </Alert>
+        {(() => {
```
Comment (pdettori) [inline kagenti/ui-v2/src/pages/ObservabilityPage.tsx:164]: **nit**: The IIFE `(() => { ... })()` in JSX is slightly unusual. Consider extracting to `useMemo` for readability. Non-blocking — works as-is.

**Review by pdettori — APPROVED** [review]
Clean, well-structured PR that adds MLflow support to the observability dashboard following the established Phoenix pattern across all layers (Helm → backend → frontend). Test coverage included. All CI green.

**Areas reviewed**: Helm/K8s, Python backend, Python tests, Frontend
**Commits**: 5 commits, all signed-off
**CI status**: All 20 checks passing

**Suggestion (non-blocking):** The IIFE `(() => { ... })()` pattern in `ObservabilityPage.tsx` (line ~164) is a bit unusual in JSX. Consider extracting the tool-list computation to a `useMemo` hook:

```tsx
const toolList = useMemo(() => {
  const tools = [
    tracesUrl && 'Phoenix for traces',
    'Kiali for service mesh',
    mlflowUrl && 'MLflow for experiment tracking',
  ].filter(Boolean) as string[];
  return tools.length <= 1
    ? tools.join('')
    : tools.length === 2
      ? tools.join(' and ')
      : `${tools.slice(0, -1).join(', ')}, and ${tools[tools.length - 1]}`;
}, [tracesUrl, mlflowUrl]);
```

Then just reference `{toolList}` in the Alert body. Current approach works fine though.
