### PR TITLE
Fix: add clickable URL links

### LINKED ISSUE #1284: URL fields are not clickable
### Feature Description

I expected the URL links in the Kagenti UI to be clickable. It seems that an `<a>` tag would be more appropriate than a `<ClipboardCopy>` or `<code>` element to represent all read-only URL fields. 

### Proposed Solution

Update `ui-v2` elements to support clickable URL links.

### Want to contribute?

- [x] I would like to work on this issue.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by kabicin**
## Summary

Updates read-only URL links in `ui-v2` to use clickable `<a>` tags. 

## (Optional) Testing Instructions

Fixes https://github.com/kagenti/kagenti/issues/1284

### CODE REVIEW

File: kagenti/ui-v2/src/pages/ToolDetailPage.tsx [hunk 1]
```diff
@@ -848,9 +846,9 @@ export const ToolDetailPage: React.FC = () => {
                   <DescriptionListGroup>
                     <DescriptionListTerm>MCP Server URL (in-cluster)</DescriptionListTerm>
                     <DescriptionListDescription>
```
Comment (pdettori) [inline kagenti/ui-v2/src/pages/ToolDetailPage.tsx:848]: **suggestion**: `mcpInClusterUrl` is a Kubernetes in-cluster URL (e.g. `http://svc.ns.svc.cluster.local:8080`) — not reachable from the user's browser. Making it a clickable `<a>` is misleading; the previous `ClipboardCopy` was more useful here since users copy it for in-cluster `curl`.

Consider keeping `ClipboardCopy` for in-cluster URLs while converting browser-accessible URLs to `<a>` tags.

File: kagenti/ui-v2/src/pages/AgentDetailPage.tsx [hunk 2]
```diff
@@ -472,9 +470,9 @@ export const AgentDetailPage: React.FC = () => {
                       <DescriptionListGroup>
                         <DescriptionListTerm>Agent URL</DescriptionListTerm>
                         <DescriptionListDescription>
```
Comment (pdettori) [inline kagenti/ui-v2/src/pages/AgentDetailPage.tsx:472]: **suggestion**: Replacing `ClipboardCopy` with a plain `<a>` drops the copy-to-clipboard UX. For URLs users frequently copy (agent URLs, MCP server URLs), consider combining both: a clickable link *with* a copy button.

PatternFly's `ClipboardCopy` supports custom children, or you could add a small copy icon next to the `<a>`. This applies to the same pattern in `ToolDetailPage.tsx` and `BuildProgressPage.tsx` as well.

File: kagenti/ui-v2/src/pages/AgentDetailPage.tsx [hunk 3]
```diff
@@ -568,12 +566,6 @@ export const AgentDetailPage: React.FC = () => {
                                         </DescriptionListDescription>
```
Comment (pdettori) [inline kagenti/ui-v2/src/pages/AgentDetailPage.tsx:566]: **praise**: Good cleanup — the removed `agentCard.url` section was a duplicate of the `agentUrl` field shown above (since `agentUrl` is derived from `agentCard?.url`).

**Review by pdettori — COMMENTED** [review]
Small, focused UI PR that converts read-only URL displays to clickable links across 7 files. All `<a>` tags properly use `target="_blank" rel="noopener noreferrer"`. Unused imports are cleaned up correctly.

The main consideration is that copy-to-clipboard functionality is lost — worth evaluating whether both clicking and copying are needed for these URLs.

**Areas reviewed**: Frontend (React/TypeScript)
**Commits**: 1 commit, signed-off: ✅
**CI status**: "Deploy & Test" failing (Keycloak auth infra issue, unrelated to this PR). All lint/security checks pass.

**Review by pdettori — APPROVED** [review]
/lgtm
